FILE_FORMAT = '.json'
FILE_AUTHOR_NAME = 'db_author' + FILE_FORMAT
FILE_BOOK_NAME = 'db_book' + FILE_FORMAT
FILE_CATEGORY_NAME = 'db_category' + FILE_FORMAT
FILE_COURSE_NAME = 'db_course' + FILE_FORMAT
FILE_USER_NAME = 'db_user' + FILE_FORMAT
FILE_STATUS_NAME = 'db_status' + FILE_FORMAT
FILE_TODO_NAME = 'db_todo' + FILE_FORMAT
FILE_VIDEO_NAME = 'db_video' + FILE_FORMAT
FILE_MODEL = 'db_model' + FILE_FORMAT
FILE_TAG = 'db_tag' + FILE_FORMAT
FILE_ROADMAP = 'db_roadmap' + FILE_FORMAT
FILE_ROADMAP_TYPE = 'db_roadmap_type' + FILE_FORMAT
FILE_ROADMAP_PRIORITY = 'db_roadmap_priority' + FILE_FORMAT
FILE_ROADMAP_COMPLEXITY = 'db_roadmap_complexity' + FILE_FORMAT
FILE_QUESTION = 'db_question' + FILE_FORMAT
FILE_ITEM = 'db_item' + FILE_FORMAT
FILE_SUBITEM = 'db_subitem' + FILE_FORMAT
FILE_LOCATION = '../../resources/data/'
FILE_CONFIG_LOCATION = 'My-CRM/src/model/config.py'
FILE_LOCATION_TAG = '../../../resources/data/'
FILE_ENCODING = 'UTF-8'
FILE_INDEX = 267
IDENTIFIER = 'id'
FORMAT_DATE = '%d.%m.%Y'
INT_JFSCF_URL = 'http://89.74.210.195:8090/jfs-cloud-app-ci/v1/api/storage/'
INT_JFSCF_TENANT_NAME = 'My-CRM'
FOLDER_IMAGES = '../../img/'
SIZE_IMAGE = 200
QUALITY_IMAGE = 85
FILE_ZIP = '../../resources/temp/'
FILES_ZIPPED = '../../resources/ZIPPED/'
FILES_DOWNLOAD_ALL = 'download/all/'
GET_FILE = 'download/'
UPLOAD_FILE = 'upload/'
